"""
initial schema.

Revision ID: aab896a5964f
Revises:
Create Date: 2026-02-22 18:37:43.599196

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aab896a5964f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("chat_jid", sa.String(), nullable=False),
        sa.Column("sender_name", sa.String(), nullable=False),
        sa.Column("is_group", sa.Boolean(), nullable=False),
        sa.Column("message_type", sa.String(), nullable=False),
        sa.Column("content_preview", sa.Text(), nullable=True),
        sa.Column("audio_local_path", sa.String(), nullable=True),
        sa.Column("audio_public_url", sa.String(), nullable=True),
        sa.Column("transcription", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "urgency",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="urgencylevel"),
            nullable=False,
        ),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("read_by_user", sa.Boolean(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processed_messages_chat_jid"), "processed_messages", ["chat_jid"], unique=False
    )
    op.create_index(
        op.f("ix_processed_messages_message_id"), "processed_messages", ["message_id"], unique=True
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vip_contacts", sa.Text(), nullable=False),
        sa.Column("urgent_keywords", sa.Text(), nullable=False),
        sa.Column("quiet_hours_start", sa.String(), nullable=False),
        sa.Column("quiet_hours_end", sa.String(), nullable=False),
        sa.Column("quiet_hours_allow_vip", sa.Boolean(), nullable=False),
        sa.Column("notify_on_group_mention", sa.Boolean(), nullable=False),
        sa.Column("group_notify_threshold", sa.Integer(), nullable=False),
        sa.Column("important_groups", sa.Text(), nullable=False),
        sa.Column("long_message_threshold", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("whisper_transcription", sa.Boolean(), nullable=False),
        sa.Column("alexa_proactive_token", sa.String(), nullable=True),
        sa.Column("alexa_proactive_token_expires", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_processed_messages_message_id"), table_name="processed_messages")
    op.drop_index(op.f("ix_processed_messages_chat_jid"), table_name="processed_messages")
    op.drop_table("processed_messages")
    # ### end Alembic commands ###
